### ISSUE TITLE
Paging doesn't appear to work on examples. 

### ISSUE THREAD

**Issue by frapps** [DevExpress-Examples/how-to-implement-crud-operations#8]
On examples such as https://github.com/DevExpress-Examples/how-to-implement-crud-operations/tree/21.2.4%2B/CS/ViewModel/EntityFramework/PagedAsyncSource  The paging doesn't appear or work. It works on the Code Behind Versions?

**Comment by Alexander-Ploskin** [comment]
Hello,

We created a separate ticket for this issue: [T1064221 - GridControl bound to PagedAsyncSource doesn't show PagerControl](https://supportcenter.devexpress.com/internal/ticket/details/t1064221). To track its progress and receive automatic status notifications, please add this ticket to your DevExpress Support Center Favorites list.

Thanks,
Alexander
